# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
markdown: kramdown

title: The Sons of Technology
email: ben@yarm.is
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sonsof.technology"
twitter_username: byarmis
github_username:  byarmis

# Build settings
remote_theme: "mmistakes/so-simple-theme"
plugins:
  - jekyll-feed
  - jekyll-paginate-v2

skin: "/assets/css/skins/dark.css"
logo: "/images/logo.png"
footer_links:
  - title: Discord
    url: https://discord.gg/dwxjufU7nH
    icon: fab fa-discord
  - title: MeetUp
    url: https://www.meetup.com/sons-of-technology/
    icon: fab fa-meetup

search_full_content: true

collections:
  rides:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: "_rides"
      type: rides
      sort_by: date
    values:
      layout: post
      comments: true
      share: true

date_format: "%B %-d, %Y"

